"""added status to todos notes

Revision ID: 88482124ecd8
Revises: 9edefbf07dd1
Create Date: 2024-05-18 17:13:16.212723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88482124ecd8'
down_revision: Union[str, None] = '9edefbf07dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('todos', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'status')
    op.drop_column('notes', 'status')
    # ### end Alembic commands ###
