"""cascade delete for notes

Revision ID: 9edefbf07dd1
Revises: 371e57045764
Create Date: 2024-05-13 01:36:31.900069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9edefbf07dd1'
down_revision: Union[str, None] = '371e57045764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notes_todo_id_fk_fkey', 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'todos', ['todo_id_fk'], ['todo_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key('notes_todo_id_fk_fkey', 'notes', 'todos', ['todo_id_fk'], ['todo_id'])
    # ### end Alembic commands ###
